### ISSUE TITLE
在linux下的UI_乱排版问题

### ISSUE THREAD

**Issue by idqaq** [alwaysmy/KicadShapeEditor#1]
![截图_2023-08-18_18-52-45](https://github.com/alwaysmy/KicadShapeEditor/assets/64400966/004a357f-8d0c-4e21-9a16-4aa446f10827)

linux + Kicad7.0

**Comment by alwaysmy** [comment]
能提供一下linux设备信息吗，还有用的什么发行版，我回去看一下问题在哪（之前我自己的manjaro下6.0的测的时候好像没有问题）

**Comment by idqaq** [comment]
操作系统: Garuda 
内核版本: 6.1.45-1-lts
设备显卡: NVIDIA NVIDIA Corporation TU117M  
-----------------------------------------------------------
Application: KiCad x86_64 on x86_64
Version: 7.0.7, release build
Libraries:
	wxWidgets 3.2.2
	FreeType 2.13.1
	HarfBuzz 8.1.1
	FontConfig 2.14.2
	libcurl/8.2.1 OpenSSL/3.1.2 zlib/1.2.13 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libpsl/0.21.2 (+libidn2/2.3.4) libssh2/1.11.0 nghttp2/1.55.1

Platform: Garuda Linux, 64 bit, Little endian, wxGTK, xfce, x11

Build Info:
	Date: Aug 15 2023 08:14:21
	wxWidgets: 3.2.2 (wchar_t,wx containers) GTK+ 3.24
	Boost: 1.81.0
	OCC: 7.6.3
	Curl: 8.2.1
	ngspice: 40
	Compiler: GCC 13.2.1 with C++ ABI 1018

Build settings:
	KICAD_USE_EGL=ON
	KICAD_SPICE=ON
=-=-=-=-=-==-=-=-=-=-=-=--=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

**Comment by alwaysmy** [comment]
> ![截图_2023-08-18_18-52-45](https://user-images.githubusercontent.com/64400966/261585716-004a357f-8d0c-4e21-9a16-4aa446f10827.png)
> 
> linux + Kicad7.0

已经修复这个问题

**Comment by idqaq** [comment]
ok!
